"""Database creation

Revision ID: 1ca8c1ebe4eb
Revises: 
Create Date: 2024-01-17 22:15:26.538463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8c1ebe4eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_assistants',
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('sys_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('table_number', 'assistant_id')
    )
    op.create_index(op.f('ix_table_assistants_assistant_id'), 'table_assistants', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_table_assistants_table_number'), 'table_assistants', ['table_number'], unique=False)
    op.create_table('tables',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'table_number')
    )
    op.create_index(op.f('ix_tables_table_number'), 'tables', ['table_number'], unique=False)
    op.create_index(op.f('ix_tables_user_id'), 'tables', ['user_id'], unique=True)
    op.create_table('threads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'assistant_id')
    )
    op.create_index(op.f('ix_threads_assistant_id'), 'threads', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_threads_user_id'), 'threads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_assistant_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_tables_user_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_table_number'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_table_assistants_table_number'), table_name='table_assistants')
    op.drop_index(op.f('ix_table_assistants_assistant_id'), table_name='table_assistants')
    op.drop_table('table_assistants')
    # ### end Alembic commands ###
