"""Database creation

Revision ID: 20b6e70455b6
Revises: 
Create Date: 2024-01-20 23:22:55.464058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b6e70455b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('assistants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assistant_id', sa.String(), nullable=False),
    sa.Column('sys_prompt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_index(op.f('ix_assistants_assistant_id'), 'assistants', ['assistant_id'], unique=False)
    op.create_table('threads',
    sa.Column('assistant_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.assistant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_thread_id'), 'threads', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_assistants_assistant_id'), table_name='assistants')
    op.drop_table('assistants')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
