"""Database creation

Revision ID: ef9c12b169ac
Revises: 
Create Date: 2024-01-18 13:24:58.856247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9c12b169ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_assistants',
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.String(), nullable=True),
    sa.Column('sys_prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('table_number')
    )
    op.create_index(op.f('ix_table_assistants_assistant_id'), 'table_assistants', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_table_assistants_table_number'), 'table_assistants', ['table_number'], unique=False)
    op.create_table('tables',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'table_number')
    )
    op.create_index(op.f('ix_tables_table_number'), 'tables', ['table_number'], unique=False)
    op.create_index(op.f('ix_tables_user_id'), 'tables', ['user_id'], unique=True)
    op.create_table('utils',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tables_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utils_tables_count'), 'utils', ['tables_count'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tables.user_id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_index(op.f('ix_threads_thread_id'), 'threads', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_utils_tables_count'), table_name='utils')
    op.drop_table('utils')
    op.drop_index(op.f('ix_tables_user_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_table_number'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_table_assistants_table_number'), table_name='table_assistants')
    op.drop_index(op.f('ix_table_assistants_assistant_id'), table_name='table_assistants')
    op.drop_table('table_assistants')
    # ### end Alembic commands ###
